#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr  8 22:15:11 2019

@author: kek25

function to create pdfs from NASS Data
"""

 def getNASSdata(countyList, year):
     #age
     #farm sizes
     #number of farms
     #number of principal operators
     #percentage of each tenure type
     
     
 def getCropProduction(year):    
     #yeild, price, acres for each crop CDL to GCAM